FROM node:18.16.1-alpine3.18

RUN apk update && apk upgrade && \
    apk add --no-cache python3 make g++ \
    && rm -rf /var/cache/apk/*

WORKDIR /usr/local/app

RUN yarn global add @angular/cli

ARG PORT
ENV PORT=$PORT

COPY package.json yarn.lock ./
RUN yarn install
COPY . .
EXPOSE $PORT

CMD ng serve --host 0.0.0.0 --port $PORT --poll 1000
