FROM node:18.16.1-alpine3.18

WORKDIR /usr/local/app

RUN yarn global add @angular/cli

ARG PORT
ENV PORT=$PORT

COPY package.json yarn.lock ./
RUN yarn install
COPY --chown=node:node . .
EXPOSE $PORT

CMD ng serve --host 0.0.0.0 --port $PORT --poll 1000
