FROM node:16-alpine3.18
WORKDIR /opt/app

COPY package.json yarn.lock ./

RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev wget
RUN wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -P /opt/scripts/
RUN chmod +x /opt/scripts/wait-for-it.sh

RUN yarn install

COPY . .

RUN ["yarn", "build"]

EXPOSE $PORT

CMD /opt/scripts/wait-for-it.sh -t 0 $DATABASE_HOST:$DATABASE_PORT -- yarn cs import --yes && yarn develop
